version: '3.7'

services:
  postgres_db:
    container_name: postgres_db
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

  # api:
  #   container_name: api-newpack
  #   build: .
  #   restart: always
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres_db
  #     - redis
  #   env_file:
  #     - .env

volumes:
  postgres_data:
  redis_data:
